### ISSUE TITLE
Exercise is incompatible with Python 3.10

### ISSUE THREAD

**Issue by qxf2** [qxf2/makemework#11]
I tried this exercise using Python 3.10 and I got the following stacktrace:

`Traceback (most recent call last):
  File "/Users/qxf2/code/makemework/venv-310-makemework/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/Users/qxf2/code/makemework/venv-310-makemework/lib/python3.10/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/Users/qxf2/code/makemework/venv-310-makemework/lib/python3.10/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/Users/qxf2/code/makemework/venv-310-makemework/lib/python3.10/site-packages/_pytest/_code/code.py", line 36, in <module>
    import pluggy
  File "/Users/qxf2/code/makemework/venv-310-makemework/lib/python3.10/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/Users/qxf2/code/makemework/venv-310-makemework/lib/python3.10/site-packages/pluggy/manager.py", line 6, in <module>
    import importlib_metadata
  File "/Users/qxf2/code/makemework/venv-310-makemework/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 471, in <module>
    __version__ = version(__name__)
  File "/Users/qxf2/code/makemework/venv-310-makemework/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 438, in version
    return distribution(package).version
  File "/Users/qxf2/code/makemework/venv-310-makemework/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 411, in distribution
    return Distribution.from_name(package)
  File "/Users/qxf2/code/makemework/venv-310-makemework/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 179, in from_name
    dists = resolver(name)
  File "<frozen importlib._bootstrap_external>", line 1473, in find_distributions
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/metadata/__init__.py", line 858, in find_distributions
    found = cls._search_paths(context.name, context.path)
AttributeError: 'str' object has no attribute 'name'
`
It would be nice to make this work with the latest Python version.

**Comment by qxf2** [comment]
I did some digging and it looks like may packages need to be upgraded to make this work with Python 3.10.0. I had to remove tesults module which does not support the latest Python 3.10.0 version.

**Comment by samahquran** [comment]
I've tested this and makemework works with python3.10

**Comment by qxf2** [comment]
Thanks @samahquran ! I have merged PR #12  to master.
